import type { Metadata } from "next";
import { Geist, Geist_Mono, Nova_Cut, Fira_Sans_Condensed } from "next/font/google";
import "./globals.css";
import DynamicHeader from "./Components/Header/DynamicHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const novaCut = Nova_Cut({
  weight: "400",
  variable: "--font-nova-cut",
  subsets: ["latin"],
});

const firaSansCondensed = Fira_Sans_Condensed({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-fira-sans-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ensemble Phaenomen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${novaCut.variable} ${firaSansCondensed.variable} antialiased`}
      >
        <DynamicHeader />
        {children}
      </body>
    </html>
  );
}
